insert into dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id)
values  (N'Son MAC Ruby Woo', N'Son lì màu đỏ', 1, N'/img/SanPham/AnhSanPham1.jpg', 1, 1, N'SP01', 1),
        (N'Son Dior Addict', N'Son bóng dưỡng ẩm', 1, N'/img/SanPham/AnhSanPham2.png', 3, 2, N'SP02', 2),
        (N'Son Test', N'Sản phẩm test cho id = 3', 1, N'/img/SanPham/AnhSanPham3.png', 4, 3, N'SP03', 3),
        (N'Oreal Rouge', N'Son lì màu đỏ cổ điển', 1, N'/img/SanPham/AnhSanPham4.png', 4, 4, N'SP04', 4),
        (N'Son YSL Tatouage', N'Son kem lì hot trend', 1, N'/img/SanPham/AnhSanPham5.png', 5, 5, N'SP05', 5),
        (N'Son Chanel Coco', N'Dòng son dưỡng có màu', 1, N'/img/SanPham/AnhSanPham6.png', 6, 6, N'SP06', 6),
        (N'Son Etude House Dear Darling', N'Son tint bóng mịn', 1, N'/img/SanPham/AnhSanPham7.png', 7, 7, N'SP07', 7),
        (N'Son Innisfree Vivid Cotton', N'Son kem mịn nhẹ', 1, N'/img/SanPham/AnhSanPham8.png', 8, 8, N'SP08', 8),
        (N'Son Maybelline SuperStay', N'Son lì lâu trôi', 1, null, 2, 1, N'SP09', 9),
        (N'Son Velvet Lip Tint', N'Son kem lì Hàn Quốc', 1, null, 3, 2, N'SP10', 10),
        (N'Son Black Rouge Air Fit', N'Son tint mịn nhẹ', 1, null, 4, 3, N'SP11', 11),
        (N'Son Bbia Last Velvet', N'Son lì mịn môi', 1, null, 1, 4, N'SP12', 12),
        (N'Son Peripera Ink Airy', N'Son tint nhẹ môi', 1, null, 6, 5, N'SP13', 13),
        (N'Son Laneige Stained Glow', N'Son dưỡng bóng', 1, null, 7, 6, N'SP14', 14),
        (N'Son Tom Ford Lip Color', N'Son cao cấp', 1, null, 8, 7, N'SP15', 15),
        (N'Son Fenty Beauty Mattemoiselle', N'Son lì sắc nét', 1, null, 5, 8, N'SP16', 16),
        (N'Son Charlotte Tilbury Pillow Talk', N'Son nude hồng đất', 1, null, 4, 1, N'SP17', 17),
        (N'Son Shu Uemura Rouge', N'Son lì Nhật Bản', 1, null, 3, 2, N'SP18', 18),
        (N'Son Clio Mad Matte', N'Son lì không trôi', 1, null, 2, 3, N'SP19', 19),
        (N'Son ColourPop Ultra Matte', N'Son lì giá tốt', 1, null, 1, 4, N'SP20', 20),
        (N'Son Romand Zero Velvet', N'Son nhẹ môi', 1, null, 6, 5, N'SP21', 21),
        (N'Son NYX Soft Matte', N'Son lì nhẹ nhàng', 1, null, 7, 6, N'SP22', 22),
        (N'Son Pat McGrath Labs', N'Son high-end', 1, null, 8, 7, N'SP23', 23),
        (N'Son Huda Beauty Power Bullet', N'Son lì Middle East', 1, null, 6, 8, N'SP24', 24),
        (N'Son Gucci Satin', N'Son satin sang trọng', 1, null, 7, 1, N'SP25', 25),
        (N'Son Armani Lip Maestro', N'Son kem lì đẳng cấp', 1, null, 8, 2, N'SP26', 26),
        (N'Son Bourjois Velvet', N'Son lì Pháp', 1, null, 4, 3, N'SP27', 27),
        (N'Son Urban Decay Vice', N'Son lì đa dạng màu', 1, null, 5, 4, N'SP28', 28),
        (N'Hoàn', N'Hoàn đẹp trai siêu cấp vip pro', 1, N'/img/SanPham/AnhSanPham98918075.png', 4, 1, N'SP45629921', 29),
        (N'sdssf', N'Hoàn', 1, null, 1, 1, N'SP07593900', 30),
        (N'ffdgdfgg', N'hfghfgh', 1, N'/img/SanPham/AnhSanPham55726526.png', 5, 8, N'SP55726526', 1002);