INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son MAC Ruby Woo', N'Son lì màu đỏ', 1, N'/img/SanPham/AnhSanPham1.jpg', 1, 1, N'SP01', 1);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Dior Addict', N'Son bóng dưỡng ẩm', 1, N'/img/SanPham/AnhSanPham2.png', 3, 2, N'SP02', 2);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Test', N'Sản phẩm test cho id = 3', 1, N'/img/SanPham/AnhSanPham3.png', 4, 3, N'SP03', 3);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Oreal Rouge', N'Son lì màu đỏ cổ điển', 1, N'/img/SanPham/AnhSanPham4.png', 4, 4, N'SP04', 4);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son YSL Tatouage', N'Son kem lì hot trend', 1, N'/img/SanPham/AnhSanPham5.png', 5, 5, N'SP05', 5);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Chanel Coco', N'Dòng son dưỡng có màu', 1, N'/img/SanPham/AnhSanPham6.png', 6, 6, N'SP06', 6);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Etude House Dear Darling', N'Son tint bóng mịn', 1, N'/img/SanPham/AnhSanPham7.png', 7, 7, N'SP07', 7);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Innisfree Vivid Cotton', N'Son kem mịn nhẹ', 1, N'/img/SanPham/AnhSanPham8.png', 8, 8, N'SP08', 8);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Maybelline SuperStay', N'Son lì lâu trôi', 1, null, 2, 1, N'SP09', 9);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Velvet Lip Tint', N'Son kem lì Hàn Quốc', 1, null, 3, 2, N'SP10', 10);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Black Rouge Air Fit', N'Son tint mịn nhẹ', 1, null, 4, 3, N'SP11', 11);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Bbia Last Velvet', N'Son lì mịn môi', 1, null, 1, 4, N'SP12', 12);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Peripera Ink Airy', N'Son tint nhẹ môi', 1, null, 6, 5, N'SP13', 13);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Laneige Stained Glow', N'Son dưỡng bóng', 1, null, 7, 6, N'SP14', 14);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Tom Ford Lip Color', N'Son cao cấp', 1, null, 8, 7, N'SP15', 15);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Fenty Beauty Mattemoiselle', N'Son lì sắc nét', 1, null, 5, 8, N'SP16', 16);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Charlotte Tilbury Pillow Talk', N'Son nude hồng đất', 1, null, 4, 1, N'SP17', 17);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Shu Uemura Rouge', N'Son lì Nhật Bản', 1, null, 3, 2, N'SP18', 18);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Clio Mad Matte', N'Son lì không trôi', 1, null, 2, 3, N'SP19', 19);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son ColourPop Ultra Matte', N'Son lì giá tốt', 1, null, 1, 4, N'SP20', 20);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Romand Zero Velvet', N'Son nhẹ môi', 1, null, 6, 5, N'SP21', 21);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son NYX Soft Matte', N'Son lì nhẹ nhàng', 1, null, 7, 6, N'SP22', 22);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Pat McGrath Labs', N'Son high-end', 1, null, 8, 7, N'SP23', 23);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Huda Beauty Power Bullet', N'Son lì Middle East', 1, null, 6, 8, N'SP24', 24);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Gucci Satin', N'Son satin sang trọng', 1, null, 7, 1, N'SP25', 25);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Armani Lip Maestro', N'Son kem lì đẳng cấp', 1, null, 8, 2, N'SP26', 26);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Bourjois Velvet', N'Son lì Pháp', 1, null, 4, 3, N'SP27', 27);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Son Urban Decay Vice', N'Son lì đa dạng màu', 1, null, 5, 4, N'SP28', 28);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'Hoàn', N'Hoàn đẹp trai siêu cấp vip pro', 1, N'/img/SanPham/AnhSanPham98918075.png', 4, 1, N'SP45629921', 29);
INSERT INTO Web_Ban_Son.dbo.SanPham (ten, moTa, trangThai, AnhSanPham, idNSX, idDongSanPham, ma, id) VALUES (N'sdssf', N'fsdfdsfdsff', 1, N'/img/SanPham/AnhSanPham07593900.png', 1, 1, N'SP07593900', 30);
